name: peppol-specifications Master Build

on: [push]

jobs:
  master-branch-build:
    if: github.ref == 'refs/heads/master' # run this job only for the master branch
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Build with Maven
          run: mvn -B --no-transfer-progress package

  milestone-6-branch-build:
    if: github.ref == 'refs/heads/milestone-6' # run this job only for the milestone-6 branch
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11
        - name: Build with Maven
          run: mvn -B --no-transfer-progress package