name: peppol-specifications Snapshot publish

on: [push]

jobs:
  master-branch-publish:
    if: github.ref == 'refs/heads/master' # run this job only for the master branch
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Maven Central Repository
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
            server-id: ossrh
            server-username: MAVEN_USERNAME
            server-password: MAVEN_PASSWORD
        - name: Publish package
          run: mvn --batch-mode deploy
          env:
            MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
            MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}


  milestone-6-branch-build:
    if: github.ref == 'refs/heads/milestone-6' # run this job only for the milestone-6 branch
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Maven Central Repository
          uses: actions/setup-java@v1
          with:
            java-version: 11
            server-id: ossrh
            server-username: MAVEN_USERNAME
            server-password: MAVEN_PASSWORD
        - name: Publish package
          run: mvn --batch-mode deploy
          env:
            MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
            MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
